Install glibc when building binaries
The pipeline currently fails with:
```
/usr/local/.ghcup/ghc/9.10.1/lib/ghc-9.10.1/lib/../lib/x86_64-linux-ghc-9.10.1/unix-2.8.5.1-e9c3/libHSunix-2.8.5.1-e9c3.a(PosixString.o):function
ghczuwrapperZC1ZCunixzm2zi8zi5zi1zme9c3ZCSystemziPosixziFilesziPosixStringZCmknod:(.text+0x37):
error: undefined reference to '__xmknod'
/usr/local/.ghcup/ghc/9.10.1/lib/ghc-9.10.1/lib/../lib/x86_64-linux-ghc-9.10.1/rts-1.0.2/libHSrts-1.0.2_thr.a(Linker.thr_o):Linker.c:function
internal_dlopen:(.text+0x72): warning: Using 'dlopen' in statically
linked applications requires at runtime the shared libraries from the
glibc version used for linking
/usr/local/.ghcup/ghc/9.10.1/lib/ghc-9.10.1/lib/../lib/x86_64-linux-ghc-9.10.1/rts-1.0.2/libHSrts-1.0.2_thr.a(Elf.thr_o):Elf.c:function
loadNativeObj_ELF:(.text+0x1f27): warning: Using 'dlopen' in statically
linked applications requires at runtime the shared libraries from the
glibc version used for linking
collect2: error: ld returned 1 exit status
ghc-9.10.1: `gcc' failed in phase `Linker'. (Exit code: 1)
```